package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name="auditoria"
    ,schema="public"
)
public class Auditoria  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String acao;
     private String modulo;
     private String dado;

    public Auditoria() {
    }

	
    public Auditoria(int id, String acao, String modulo) {
        this.id = id;
        this.acao = acao;
        this.modulo = modulo;
    }
    public Auditoria(int id, Usuario usuario, String acao, String modulo, String dado) {
       this.id = id;
       this.usuario = usuario;
       this.acao = acao;
       this.modulo = modulo;
       this.dado = dado;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="acao", nullable=false, length=1000)
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }

    
    @Column(name="modulo", nullable=false, length=30)
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    
    @Column(name="dado", length=1000)
    public String getDado() {
        return this.dado;
    }
    
    public void setDado(String dado) {
        this.dado = dado;
    }




}


