package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", schema = "public"
)
public class Banco implements java.io.Serializable {

    @JsonView({Folha.FuncionarioFicha.class})

    private int id;
    @JsonView({Folha.FuncionarioFicha.class})

    private String nome;
    private String numero;
    private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

    public Banco() {
    }

    public Banco(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }

    public Banco(int id, String nome, String numero, Set<Funcionario> funcionarios) {
        this.id = id;
        this.nome = nome;
        this.numero = numero;
        this.funcionarios = funcionarios;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nome", nullable = false, length = 100)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "numero")
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

}
