package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CargoHasEventoId generated by hbm2java
 */
@Embeddable
public class CargoHasEventoId  implements java.io.Serializable {


     private int cargoId;
     private int eventoId;

    public CargoHasEventoId() {
    }

    public CargoHasEventoId(int cargoId, int eventoId) {
       this.cargoId = cargoId;
       this.eventoId = eventoId;
    }
   


    @Column(name="cargo_id", nullable=false)
    public int getCargoId() {
        return this.cargoId;
    }
    
    public void setCargoId(int cargoId) {
        this.cargoId = cargoId;
    }


    @Column(name="evento_id", nullable=false)
    public int getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CargoHasEventoId) ) return false;
		 CargoHasEventoId castOther = ( CargoHasEventoId ) other; 
         
		 return (this.getCargoId()==castOther.getCargoId())
 && (this.getEventoId()==castOther.getEventoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCargoId();
         result = 37 * result + this.getEventoId();
         return result;
   }   


}


