package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CargoHasEvento generated by hbm2java
 */
@Entity
@Table(name="cargo_has_evento"
    ,schema="public"
)
public class CargoHasEvento  implements java.io.Serializable {


     private CargoHasEventoId id;
     private int referencia;
     private Cargo cargo;
     private Evento evento;
     private Date dataInicio;
     private Date dataFim;
     private boolean excluido;

    public CargoHasEvento() {
    }

	
    public CargoHasEvento(CargoHasEventoId id, Cargo cargo, Evento evento, Date dataInicio) {
        this.id = id;
        this.cargo = cargo;
        this.evento = evento;
        this.dataInicio = dataInicio;
    }
    public CargoHasEvento(CargoHasEventoId id, Cargo cargo, Evento evento, Date dataInicio, Date dataFim) {
       this.id = id;
       this.cargo = cargo;
       this.evento = evento;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cargoId", column=@Column(name="cargo_id", nullable=false) ), 
        @AttributeOverride(name="eventoId", column=@Column(name="evento_id", nullable=false) ) } )
    public CargoHasEventoId getId() {
        return this.id;
    }
    
    public void setId(CargoHasEventoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargo_id", nullable=false, insertable=false, updatable=false)
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_id", nullable=false, insertable=false, updatable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_fim", length=13)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    public int getReferencia() {
        return referencia;
    }

    public void setReferencia(int referencia) {
        this.referencia = referencia;
    }

    public boolean isExcluido() {
        return excluido;
    }

    public void setExcluido(boolean excluido) {
        this.excluido = excluido;
    }




}


