package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cbo generated by hbm2java
 */
@Entity
@Table(name="cbo"
    ,schema="public"
)
public class Cbo  implements java.io.Serializable {

@JsonView({Folha.FuncionarioFicha.class})
     private int id;
@JsonView({Folha.FuncionarioFicha.class})
     private String nome;
     private String descricaoSumarizada;
     private Set<Cargo> cargos = new HashSet<Cargo>(0);

    public Cbo() {
    }

	
    public Cbo(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Cbo(int id, String nome, String descricaoSumarizada, Set<Cargo> cargos) {
       this.id = id;
       this.nome = nome;
       this.descricaoSumarizada = descricaoSumarizada;
       this.cargos = cargos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=500)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao_sumarizada", length=1000)
    public String getDescricaoSumarizada() {
        return this.descricaoSumarizada;
    }
    
    public void setDescricaoSumarizada(String descricaoSumarizada) {
        this.descricaoSumarizada = descricaoSumarizada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cbo")
    public Set<Cargo> getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set<Cargo> cargos) {
        this.cargos = cargos;
    }




}


