package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cbo generated by hbm2java
 */
@Entity
@Table(name="cbo"
    ,schema="public"
)
public class Cbo  implements java.io.Serializable {


     private int id;
     private String nome;
     private String decricaoSumarizada;
     private Set<Cargo> cargos = new HashSet<Cargo>(0);

    public Cbo() {
    }

	
    public Cbo(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Cbo(int id, String nome, String decricaoSumarizada, Set<Cargo> cargos) {
       this.id = id;
       this.nome = nome;
       this.decricaoSumarizada = decricaoSumarizada;
       this.cargos = cargos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=500)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="decricao_sumarizada", length=1000)
    public String getDecricaoSumarizada() {
        return this.decricaoSumarizada;
    }
    
    public void setDecricaoSumarizada(String decricaoSumarizada) {
        this.decricaoSumarizada = decricaoSumarizada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cbo")
    public Set<Cargo> getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set<Cargo> cargos) {
        this.cargos = cargos;
    }




}


