package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurriculoExperiencia generated by hbm2java
 */
@Entity
@Table(name="curriculo_experiencia"
    ,schema="public"
)
public class CurriculoExperiencia  implements java.io.Serializable {


     private int id;
     private Pessoa pessoa;
     private String atribuicao;
     private Date dataInicial;
     private Date dataFinal;
     private String pessoaReferencia;
     private String pessoaContato;
     private String empresa;

    public CurriculoExperiencia() {
    }

	
    public CurriculoExperiencia(int id, Pessoa pessoa, Date dataInicial) {
        this.id = id;
        this.pessoa = pessoa;
        this.dataInicial = dataInicial;
    }
    public CurriculoExperiencia(int id, Pessoa pessoa, String atribuicao, Date dataInicial, Date dataFinal, String pessoaReferencia, String pessoaContato, String empresa) {
       this.id = id;
       this.pessoa = pessoa;
       this.atribuicao = atribuicao;
       this.dataInicial = dataInicial;
       this.dataFinal = dataFinal;
       this.pessoaReferencia = pessoaReferencia;
       this.pessoaContato = pessoaContato;
       this.empresa = empresa;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="atribuicao")
    public String getAtribuicao() {
        return this.atribuicao;
    }
    
    public void setAtribuicao(String atribuicao) {
        this.atribuicao = atribuicao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicial", nullable=false, length=13)
    public Date getDataInicial() {
        return this.dataInicial;
    }
    
    public void setDataInicial(Date dataInicial) {
        this.dataInicial = dataInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_final", length=13)
    public Date getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }

    
    @Column(name="pessoa_referencia", length=100)
    public String getPessoaReferencia() {
        return this.pessoaReferencia;
    }
    
    public void setPessoaReferencia(String pessoaReferencia) {
        this.pessoaReferencia = pessoaReferencia;
    }

    
    @Column(name="pessoa_contato", length=100)
    public String getPessoaContato() {
        return this.pessoaContato;
    }
    
    public void setPessoaContato(String pessoaContato) {
        this.pessoaContato = pessoaContato;
    }

    
    @Column(name="empresa", length=500)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }




}


