package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dependente generated by hbm2java
 */
@Entity
@Table(name="dependente"
    ,schema="public"
)
public class Dependente  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private Pessoa pessoa;
     private TipoSanguineo tipoSanguineo;
     private Date dataInicial;
     private Date dataFim;

    public Dependente() {
    }

	
    public Dependente(int id, Funcionario funcionario, Pessoa pessoa, TipoSanguineo tipoSanguineo, Date dataInicial) {
        this.id = id;
        this.funcionario = funcionario;
        this.pessoa = pessoa;
        this.tipoSanguineo = tipoSanguineo;
        this.dataInicial = dataInicial;
    }
    public Dependente(int id, Funcionario funcionario, Pessoa pessoa, TipoSanguineo tipoSanguineo, Date dataInicial, Date dataFim) {
       this.id = id;
       this.funcionario = funcionario;
       this.pessoa = pessoa;
       this.tipoSanguineo = tipoSanguineo;
       this.dataInicial = dataInicial;
       this.dataFim = dataFim;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_pessoa_id", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_sanguineo_id", nullable=false)
    public TipoSanguineo getTipoSanguineo() {
        return this.tipoSanguineo;
    }
    
    public void setTipoSanguineo(TipoSanguineo tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicial", nullable=false, length=13)
    public Date getDataInicial() {
        return this.dataInicial;
    }
    
    public void setDataInicial(Date dataInicial) {
        this.dataInicial = dataInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_fim", length=13)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }




}


