package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entrevista generated by hbm2java
 */
@Entity
@Table(name="entrevista"
    ,schema="public"
)
public class Entrevista  implements java.io.Serializable {


     private int id;
     private Candidato candidato;
     private Pessoa pessoa;
     private Date dataProgramada;
     private Date hora;
     private boolean confirmado;
     private String descricao;
     private String resposta;
     private String localEntrevista;
     private Character situacao;

    public Entrevista() {
    }

	
    public Entrevista(int id, Candidato candidato, Pessoa pessoa, Date dataProgramada, Date hora, boolean confirmado, String descricao) {
        this.id = id;
        this.candidato = candidato;
        this.pessoa = pessoa;
        this.dataProgramada = dataProgramada;
        this.hora = hora;
        this.confirmado = confirmado;
        this.descricao = descricao;
    }
    public Entrevista(int id, Candidato candidato, Pessoa pessoa, Date dataProgramada, Date hora, boolean confirmado, String descricao, String resposta, String localEntrevista, Character situacao) {
       this.id = id;
       this.candidato = candidato;
       this.pessoa = pessoa;
       this.dataProgramada = dataProgramada;
       this.hora = hora;
       this.confirmado = confirmado;
       this.descricao = descricao;
       this.resposta = resposta;
       this.localEntrevista = localEntrevista;
       this.situacao = situacao;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidato_id", nullable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_programada", nullable=false, length=13)
    public Date getDataProgramada() {
        return this.dataProgramada;
    }
    
    public void setDataProgramada(Date dataProgramada) {
        this.dataProgramada = dataProgramada;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora", nullable=false, length=15)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    
    @Column(name="confirmado", nullable=false)
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="resposta")
    public String getResposta() {
        return this.resposta;
    }
    
    public void setResposta(String resposta) {
        this.resposta = resposta;
    }

    
    @Column(name="local_entrevista", length=100)
    public String getLocalEntrevista() {
        return this.localEntrevista;
    }
    
    public void setLocalEntrevista(String localEntrevista) {
        this.localEntrevista = localEntrevista;
    }

    
    @Column(name="situacao", length=1)
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }




}


