package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntrevistaId generated by hbm2java
 */
@Embeddable
public class EntrevistaId  implements java.io.Serializable {


     private int id;
     private int pessoaId;

    public EntrevistaId() {
    }

    public EntrevistaId(int id, int pessoaId) {
       this.id = id;
       this.pessoaId = pessoaId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="pessoa_id", nullable=false)
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntrevistaId) ) return false;
		 EntrevistaId castOther = ( EntrevistaId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getPessoaId()==castOther.getPessoaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getPessoaId();
         return result;
   }   


}


