package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventoFuncionario generated by hbm2java
 */
@Entity
@Table(name = "evento_funcionario", schema = "public"
)
@SequenceGenerator(name = "evento_funcionario_seq", sequenceName = "evento_funcionario_seq", initialValue = 1, allocationSize = 1)

public class EventoFuncionario implements java.io.Serializable {

    @JsonView(Folha.FuncionarioEvento.class)
    private int id;
    @JsonView(Folha.FuncionarioEvento.class)
    private Evento evento;
    private FuncionarioCargo funcionarioCargo;
    @JsonView(Folha.FuncionarioEvento.class)
    private Date dataInicio;
    @JsonView(Folha.FuncionarioEvento.class)
    private Date dataFim;

    private double referencia;
    private boolean mensal;

    private boolean excluido;
    public EventoFuncionario() {
    }

    public EventoFuncionario(int id, Evento evento, FuncionarioCargo funcionarioCargo, Date dataInicio) {
        this.id = id;
        this.evento = evento;
        this.funcionarioCargo = funcionarioCargo;
        this.dataInicio = dataInicio;
    }

    public EventoFuncionario(int id, Evento evento, FuncionarioCargo funcionarioCargo, Date dataInicio, Date dataFim) {
        this.id = id;
        this.evento = evento;
        this.funcionarioCargo = funcionarioCargo;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
    }

    @Id
    @GeneratedValue(generator = "evento_funcionario_seq", strategy = GenerationType.SEQUENCE)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "evento_id", nullable = false)
    public Evento getEvento() {
        return this.evento;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionario_cargo_id", nullable = false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }

    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_inicio", nullable = false, length = 13)
    public Date getDataInicio() {
        return this.dataInicio;
    }

    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_fim", length = 13)
    public Date getDataFim() {
        return this.dataFim;
    }

    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    public double getReferencia() {
        return referencia;
    }

    public void setReferencia(double referencia) {
        this.referencia = referencia;
    }

    public boolean isMensal() {
        return mensal;
    }

    public void setMensal(boolean mensal) {
        this.mensal = mensal;
    }

    public boolean isExcluido() {
        return excluido;
    }

    public void setExcluido(boolean excluido) {
        this.excluido = excluido;
    }

}
