package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;

/**
 * EventoFuncionario generated by hbm2java
 */
@Entity
@Table(name = "evento_dependencia", schema = "public"
)
@SequenceGenerator(name = "seq_evento_dependencia", sequenceName = "seq_evento_dependencia", initialValue = 1, allocationSize = 1)

public class EventoDependencia implements java.io.Serializable {

    private int id;
    private Evento evento;
    private Evento eventoDependencia;
    private String nomeVariavel;

    public EventoDependencia() {
    }

    @Id
    @GeneratedValue(generator = "seq_evento_dependencia", strategy = GenerationType.SEQUENCE)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "evento_id", nullable = false)
    public Evento getEvento() {
        return this.evento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "evento_dependencia_id", nullable = false)
    public Evento getEventoDependencia() {
        return eventoDependencia;
    }

    public void setEventoDependencia(Evento eventoDependencia) {
        this.eventoDependencia = eventoDependencia;
    }

    @Column(name = "nome_variavel", length = 100)

    public String getNomeVariavel() {
        return nomeVariavel;
    }

    public void setNomeVariavel(String nomeVariavel) {
        this.nomeVariavel = nomeVariavel;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
    }

}
