package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Type;

/**
 * EventoFuncionario generated by hbm2java
 */
@Entity
@Table(name = "evento_dependencia", schema = "public"
)
@SequenceGenerator(name = "evento_dependencia_seq", sequenceName = "evento_dependencia_seq", initialValue = 1, allocationSize = 1)

@IdClass(EventoDependenciaId.class)
public class EventoDependencia implements java.io.Serializable {

//     private EventoDependenciaId id;
    @JsonIgnore
    @Id
    private Evento evento;
    @Id
    private Evento eventoDependencia;

    private String nomeVariavel;

    public EventoDependencia() {
    }

//    @EmbeddedId
//
//    @AttributeOverrides({
//        @AttributeOverride(name = "eventoDependenciaId", column = @Column(name = "evento_dependencia_id", unique = true, nullable = false)),
////        @AttributeOverride(name = "eventoId", column = @Column(name = "evento_id", unique = true, nullable = false))})
//    @Id
//    @GeneratedValue(generator = "evento_dependencia_seq", strategy = GenerationType.SEQUENCE)
//
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//    @JoinColumn(name = "evento_dependencia_id",  nullable = false)
//    public Evento getEventoDependencia() {
//        return this.eventoDependencia;
//    }
//
//    public void setEventoDependencia(Evento eventoDependencia) {
//        this.eventoDependencia = eventoDependencia;
//    }
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "evento_id", nullable = false)
//    public Evento getEvento() {
//        return this.evento;
//    }
//
//    public void setEvento(Evento eventoByEventoId) {
//        this.evento = eventoByEventoId;
//    }
//
//    @Column(name = "nome_variavel", length = 100)
//    public String getNomeVariavel() {
//        return this.nomeVariavel;
//    }
//
//    public void setNomeVariavel(String nomeVariavel) {
//        this.nomeVariavel = nomeVariavel;
//    }
    public Evento getEvento() {
        return evento;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    public Evento getEventoDependencia() {
        return eventoDependencia;
    }

    public void setEventoDependencia(Evento eventoDependencia) {
        this.eventoDependencia = eventoDependencia;
    }

    public String getNomeVariavel() {
        return nomeVariavel;
    }

    public void setNomeVariavel(String nomeVariavel) {
        this.nomeVariavel = nomeVariavel;
    }

}
