package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ferias generated by hbm2java
 */
@Entity
@Table(name="ferias"
    ,schema="public"
)
public class Ferias  implements java.io.Serializable {


     private int id;
     private FuncionarioCargo funcionarioCargo;
     private Date dataGozoInicio;
     private Date dataGozoFim;
     private Date dataAquisitivoInicio;
     private Date dataAquisitivoFim;

    public Ferias() {
    }

    public Ferias(int id, FuncionarioCargo funcionarioCargo, Date dataGozoInicio, Date dataGozoFim, Date dataAquisitivoInicio, Date dataAquisitivoFim) {
       this.id = id;
       this.funcionarioCargo = funcionarioCargo;
       this.dataGozoInicio = dataGozoInicio;
       this.dataGozoFim = dataGozoFim;
       this.dataAquisitivoInicio = dataAquisitivoInicio;
       this.dataAquisitivoFim = dataAquisitivoFim;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_gozo_inicio", nullable=false, length=13)
    public Date getDataGozoInicio() {
        return this.dataGozoInicio;
    }
    
    public void setDataGozoInicio(Date dataGozoInicio) {
        this.dataGozoInicio = dataGozoInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_gozo_fim", nullable=false, length=13)
    public Date getDataGozoFim() {
        return this.dataGozoFim;
    }
    
    public void setDataGozoFim(Date dataGozoFim) {
        this.dataGozoFim = dataGozoFim;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_aquisitivo_inicio", nullable=false, length=13)
    public Date getDataAquisitivoInicio() {
        return this.dataAquisitivoInicio;
    }
    
    public void setDataAquisitivoInicio(Date dataAquisitivoInicio) {
        this.dataAquisitivoInicio = dataAquisitivoInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_aquisitivo_fim", nullable=false, length=13)
    public Date getDataAquisitivoFim() {
        return this.dataAquisitivoFim;
    }
    
    public void setDataAquisitivoFim(Date dataAquisitivoFim) {
        this.dataAquisitivoFim = dataAquisitivoFim;
    }




}


