package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FolhaCalculada generated by hbm2java
 */
@Entity
@Table(name="folha_calculada"
    ,schema="public"
)
public class FolhaCalculada  implements java.io.Serializable {


     private int id;
     private FuncionarioCargo funcionarioCargo;
     private Date dataReferente;
     private int dataGerado;
     private Set<FolhaCalculadaEvento> folhaCalculadaEventos = new HashSet<FolhaCalculadaEvento>(0);

    public FolhaCalculada() {
    }

	
    public FolhaCalculada(int id, FuncionarioCargo funcionarioCargo, Date dataReferente, int dataGerado) {
        this.id = id;
        this.funcionarioCargo = funcionarioCargo;
        this.dataReferente = dataReferente;
        this.dataGerado = dataGerado;
    }
    public FolhaCalculada(int id, FuncionarioCargo funcionarioCargo, Date dataReferente, int dataGerado, Set<FolhaCalculadaEvento> folhaCalculadaEventos) {
       this.id = id;
       this.funcionarioCargo = funcionarioCargo;
       this.dataReferente = dataReferente;
       this.dataGerado = dataGerado;
       this.folhaCalculadaEventos = folhaCalculadaEventos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_referente", nullable=false, length=13)
    public Date getDataReferente() {
        return this.dataReferente;
    }
    
    public void setDataReferente(Date dataReferente) {
        this.dataReferente = dataReferente;
    }

    
    @Column(name="data_gerado", nullable=false)
    public int getDataGerado() {
        return this.dataGerado;
    }
    
    public void setDataGerado(int dataGerado) {
        this.dataGerado = dataGerado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="folhaCalculada")
    public Set<FolhaCalculadaEvento> getFolhaCalculadaEventos() {
        return this.folhaCalculadaEventos;
    }
    
    public void setFolhaCalculadaEventos(Set<FolhaCalculadaEvento> folhaCalculadaEventos) {
        this.folhaCalculadaEventos = folhaCalculadaEventos;
    }




}


