package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioCargoHasMotivoFalta generated by hbm2java
 */
@Entity
@Table(name = "funcionario_cargo_has_motivo_falta", schema = "public"
)
@SequenceGenerator(name = "funcionario_cargo_has_motivo_falta_seq", sequenceName = "funcionario_cargo_has_motivo_falta_seq", initialValue = 1, allocationSize = 1)
public class FuncionarioCargoHasMotivoFalta implements java.io.Serializable {

    @JsonView({Folha.FuncionarioFicha.class})
    private int id;

    private FuncionarioCargo funcionarioCargo;
    @JsonView({Folha.FuncionarioFicha.class})

    private MotivoFalta motivoFalta;
    @JsonView({Folha.FuncionarioFicha.class})

    private Date dataInicio;
    @JsonView({Folha.FuncionarioFicha.class})

    private Date dataFinal;
    @JsonView({Folha.FuncionarioFicha.class})

    private String atestado;
    @JsonView({Folha.FuncionarioFicha.class})

    private String documentoArquivo;
    @JsonView({Folha.FuncionarioFicha.class})

    private Date dataRecebimento;
    @JsonView({Folha.FuncionarioFicha.class})

    private String documentoCid;

    public FuncionarioCargoHasMotivoFalta() {
    }

    @Id
    @GeneratedValue(generator = "funcionario_cargo_has_motivo_falta_seq", strategy = GenerationType.SEQUENCE)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionario_cargo_id", nullable = false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }

    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "motivo_falta_id", nullable = false)
    public MotivoFalta getMotivoFalta() {
        return this.motivoFalta;
    }

    public void setMotivoFalta(MotivoFalta motivoFalta) {
        this.motivoFalta = motivoFalta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_inicio", nullable = false, length = 13)
    public Date getDataInicio() {
        return this.dataInicio;
    }

    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_final", nullable = false, length = 13)
    public Date getDataFinal() {
        return this.dataFinal;
    }

    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }

    @Column(name = "atestado", nullable = true, length = 100)
    public String getAtestado() {
        return this.atestado;
    }

    public void setAtestado(String atestado) {
        this.atestado = atestado;
    }

    @Column(name = "documento_arquivo", nullable = true, length = 300)
    public String getDocumentoArquivo() {
        return this.documentoArquivo;
    }

    public void setDocumentoArquivo(String documentoArquivo) {
        this.documentoArquivo = documentoArquivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_recebimento", length = 13)
    public Date getDataRecebimento() {
        return this.dataRecebimento;
    }

    public void setDataRecebimento(Date dataRecebimento) {
        this.dataRecebimento = dataRecebimento;
    }

    @Column(name = "documento_cid", nullable = true, length = 100)
    public String getDocumentoCid() {
        return this.documentoCid;
    }

    public void setDocumentoCid(String documentoCid) {
        this.documentoCid = documentoCid;
    }

}
