package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioCargoHasMotivoFalta generated by hbm2java
 */
@Entity
@Table(name="funcionario_cargo_has_motivo_falta"
    ,schema="public"
)
public class FuncionarioCargoHasMotivoFalta  implements java.io.Serializable {


     private FuncionarioCargoHasMotivoFaltaId id;
     private FuncionarioCargo funcionarioCargo;
     private MotivoFalta motivoFalta;
     private Date dataInicio;
     private Date dataFinal;
     private String atestado;
     private String documentoArquivo;
     private Date dataRecebimento;
     private String documentoCid;

    public FuncionarioCargoHasMotivoFalta() {
    }

	
    public FuncionarioCargoHasMotivoFalta(FuncionarioCargoHasMotivoFaltaId id, FuncionarioCargo funcionarioCargo, MotivoFalta motivoFalta, Date dataInicio, Date dataFinal, String atestado, String documentoArquivo, String documentoCid) {
        this.id = id;
        this.funcionarioCargo = funcionarioCargo;
        this.motivoFalta = motivoFalta;
        this.dataInicio = dataInicio;
        this.dataFinal = dataFinal;
        this.atestado = atestado;
        this.documentoArquivo = documentoArquivo;
        this.documentoCid = documentoCid;
    }
    public FuncionarioCargoHasMotivoFalta(FuncionarioCargoHasMotivoFaltaId id, FuncionarioCargo funcionarioCargo, MotivoFalta motivoFalta, Date dataInicio, Date dataFinal, String atestado, String documentoArquivo, Date dataRecebimento, String documentoCid) {
       this.id = id;
       this.funcionarioCargo = funcionarioCargo;
       this.motivoFalta = motivoFalta;
       this.dataInicio = dataInicio;
       this.dataFinal = dataFinal;
       this.atestado = atestado;
       this.documentoArquivo = documentoArquivo;
       this.dataRecebimento = dataRecebimento;
       this.documentoCid = documentoCid;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="funcionarioCargoId", column=@Column(name="funcionario_cargo_id", nullable=false) ), 
        @AttributeOverride(name="motivoFaltaId", column=@Column(name="motivo_falta_id", nullable=false) ) } )
    public FuncionarioCargoHasMotivoFaltaId getId() {
        return this.id;
    }
    
    public void setId(FuncionarioCargoHasMotivoFaltaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false, insertable=false, updatable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="motivo_falta_id", nullable=false, insertable=false, updatable=false)
    public MotivoFalta getMotivoFalta() {
        return this.motivoFalta;
    }
    
    public void setMotivoFalta(MotivoFalta motivoFalta) {
        this.motivoFalta = motivoFalta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_final", nullable=false, length=13)
    public Date getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }

    
    @Column(name="atestado", nullable=false, length=100)
    public String getAtestado() {
        return this.atestado;
    }
    
    public void setAtestado(String atestado) {
        this.atestado = atestado;
    }

    
    @Column(name="documento_arquivo", nullable=false, length=300)
    public String getDocumentoArquivo() {
        return this.documentoArquivo;
    }
    
    public void setDocumentoArquivo(String documentoArquivo) {
        this.documentoArquivo = documentoArquivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_recebimento", length=13)
    public Date getDataRecebimento() {
        return this.dataRecebimento;
    }
    
    public void setDataRecebimento(Date dataRecebimento) {
        this.dataRecebimento = dataRecebimento;
    }

    
    @Column(name="documento_cid", nullable=false, length=100)
    public String getDocumentoCid() {
        return this.documentoCid;
    }
    
    public void setDocumentoCid(String documentoCid) {
        this.documentoCid = documentoCid;
    }




}


