package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionarioCargoHasAdvertenciaTipoId generated by hbm2java
 */
@Embeddable
public class FuncionarioCargoHasAdvertenciaTipoId  implements java.io.Serializable {


     private int funcionarioCargoId;
     private int advertenciaTipoId;

    public FuncionarioCargoHasAdvertenciaTipoId() {
    }

    public FuncionarioCargoHasAdvertenciaTipoId(int funcionarioCargoId, int advertenciaTipoId) {
       this.funcionarioCargoId = funcionarioCargoId;
       this.advertenciaTipoId = advertenciaTipoId;
    }
   


    @Column(name="funcionario_cargo_id", nullable=false)
    public int getFuncionarioCargoId() {
        return this.funcionarioCargoId;
    }
    
    public void setFuncionarioCargoId(int funcionarioCargoId) {
        this.funcionarioCargoId = funcionarioCargoId;
    }


    @Column(name="advertencia_tipo_id", nullable=false)
    public int getAdvertenciaTipoId() {
        return this.advertenciaTipoId;
    }
    
    public void setAdvertenciaTipoId(int advertenciaTipoId) {
        this.advertenciaTipoId = advertenciaTipoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionarioCargoHasAdvertenciaTipoId) ) return false;
		 FuncionarioCargoHasAdvertenciaTipoId castOther = ( FuncionarioCargoHasAdvertenciaTipoId ) other; 
         
		 return (this.getFuncionarioCargoId()==castOther.getFuncionarioCargoId())
 && (this.getAdvertenciaTipoId()==castOther.getAdvertenciaTipoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFuncionarioCargoId();
         result = 37 * result + this.getAdvertenciaTipoId();
         return result;
   }   


}


