package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioCargoHasAdvertenciaTipo generated by hbm2java
 */
@Entity
@Table(name="funcionario_cargo_has_advertencia_tipo"
    ,schema="public"
)
public class FuncionarioCargoHasAdvertenciaTipo  implements java.io.Serializable {


     private FuncionarioCargoHasAdvertenciaTipoId id;
     private AdvertenciaTipo advertenciaTipo;
     private FuncionarioCargo funcionarioCargo;
     private Date dataOcorrencia;
     private String descricao;

    public FuncionarioCargoHasAdvertenciaTipo() {
    }

    public FuncionarioCargoHasAdvertenciaTipo(FuncionarioCargoHasAdvertenciaTipoId id, AdvertenciaTipo advertenciaTipo, FuncionarioCargo funcionarioCargo, Date dataOcorrencia, String descricao) {
       this.id = id;
       this.advertenciaTipo = advertenciaTipo;
       this.funcionarioCargo = funcionarioCargo;
       this.dataOcorrencia = dataOcorrencia;
       this.descricao = descricao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="funcionarioCargoId", column=@Column(name="funcionario_cargo_id", nullable=false) ), 
        @AttributeOverride(name="advertenciaTipoId", column=@Column(name="advertencia_tipo_id", nullable=false) ) } )
    public FuncionarioCargoHasAdvertenciaTipoId getId() {
        return this.id;
    }
    
    public void setId(FuncionarioCargoHasAdvertenciaTipoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="advertencia_tipo_id", nullable=false, insertable=false, updatable=false)
    public AdvertenciaTipo getAdvertenciaTipo() {
        return this.advertenciaTipo;
    }
    
    public void setAdvertenciaTipo(AdvertenciaTipo advertenciaTipo) {
        this.advertenciaTipo = advertenciaTipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false, insertable=false, updatable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ocorrencia", nullable=false, length=13)
    public Date getDataOcorrencia() {
        return this.dataOcorrencia;
    }
    
    public void setDataOcorrencia(Date dataOcorrencia) {
        this.dataOcorrencia = dataOcorrencia;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


