package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioCargoHasAdvertenciaTipo generated by hbm2java
 */
@Entity
@Table(name = "funcionario_cargo_has_advertencia_tipo", schema = "public"
)
@SequenceGenerator(name = "funcionario_cargo_has_advertencia_seq", sequenceName = "funcionario_cargo_has_advertencia_seq", initialValue = 1, allocationSize = 1)

public class FuncionarioCargoHasAdvertenciaTipo implements java.io.Serializable {

    @JsonView({Folha.FuncionarioFicha.class})
    private int id;
    @JsonView({Folha.FuncionarioFicha.class})
    private AdvertenciaTipo advertenciaTipo;
    private FuncionarioCargo funcionarioCargo;
    @JsonView({Folha.FuncionarioFicha.class})
    private Date dataOcorrencia;
    @JsonView({Folha.FuncionarioFicha.class})
    private String descricao;

    public FuncionarioCargoHasAdvertenciaTipo() {
    }

    @Id
    @GeneratedValue(generator = "funcionario_cargo_has_advertencia_seq", strategy = GenerationType.SEQUENCE)

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "advertencia_tipo_id", nullable = false)
    public AdvertenciaTipo getAdvertenciaTipo() {
        return this.advertenciaTipo;
    }

    public void setAdvertenciaTipo(AdvertenciaTipo advertenciaTipo) {
        this.advertenciaTipo = advertenciaTipo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionario_cargo_id", nullable = false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }

    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_ocorrencia", nullable = false, length = 13)
    public Date getDataOcorrencia() {
        return this.dataOcorrencia;
    }

    public void setDataOcorrencia(Date dataOcorrencia) {
        this.dataOcorrencia = dataOcorrencia;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
