package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioAcidente generated by hbm2java
 */
@Entity
@Table(name = "funcionario_acidente", schema = "public"
)

@SequenceGenerator(name = "funcionario_acidente_seq", sequenceName = "funcionario_acidente_seq", initialValue = 1, allocationSize = 1)

public class FuncionarioAcidente implements java.io.Serializable {

    @JsonView({Folha.FuncionarioFicha.class})

    private int id;
    private FuncionarioCargo funcionarioCargo;
    @JsonView({Folha.FuncionarioFicha.class})

    private int nivelLesao;
    @JsonView({Folha.FuncionarioFicha.class})
    private double perdaPorcentagem;
    @JsonView({Folha.FuncionarioFicha.class})
    private String descricao;
    @JsonView({Folha.FuncionarioFicha.class})
    private Date dataOcorrencia;

    public FuncionarioAcidente() {
    }


    @Id

    @GeneratedValue(generator = "funcionario_acidente_seq", strategy = GenerationType.SEQUENCE)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionario_cargo_id", nullable = false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }

    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    @Column(name = "nivel_lesao", nullable = false)
    public int getNivelLesao() {
        return this.nivelLesao;
    }

    public void setNivelLesao(int nivelLesao) {
        this.nivelLesao = nivelLesao;
    }

    @Column(name = "perda_porcentagem", nullable = false)
    public double getPerdaPorcentagem() {
        return this.perdaPorcentagem;
    }

    public void setPerdaPorcentagem(double perdaPorcentagem) {
        this.perdaPorcentagem = perdaPorcentagem;
    }

    @Column(name = "descricao", nullable = false, length = 500)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_ocorrencia", nullable = false, length = 13)
    public Date getDataOcorrencia() {
        return this.dataOcorrencia;
    }

    public void setDataOcorrencia(Date dataOcorrencia) {
        this.dataOcorrencia = dataOcorrencia;
    }

}
