package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionarioCargoHasMotivoFaltaId generated by hbm2java
 */
@Embeddable
public class FuncionarioCargoHasMotivoFaltaId  implements java.io.Serializable {
     private int funcionarioCargoId;
     private int motivoFaltaId;
    public FuncionarioCargoHasMotivoFaltaId() {
    }

    public FuncionarioCargoHasMotivoFaltaId(int funcionarioCargoId, int motivoFaltaId) {
       this.funcionarioCargoId = funcionarioCargoId;
       this.motivoFaltaId = motivoFaltaId;
    }
   


    @Column(name="funcionario_cargo_id", nullable=false)
    public int getFuncionarioCargoId() {
        return this.funcionarioCargoId;
    }
    
    public void setFuncionarioCargoId(int funcionarioCargoId) {
        this.funcionarioCargoId = funcionarioCargoId;
    }


    @Column(name="motivo_falta_id", nullable=false)
    public int getMotivoFaltaId() {
        return this.motivoFaltaId;
    }
    
    public void setMotivoFaltaId(int motivoFaltaId) {
        this.motivoFaltaId = motivoFaltaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionarioCargoHasMotivoFaltaId) ) return false;
		 FuncionarioCargoHasMotivoFaltaId castOther = ( FuncionarioCargoHasMotivoFaltaId ) other; 
         
		 return (this.getFuncionarioCargoId()==castOther.getFuncionarioCargoId())
 && (this.getMotivoFaltaId()==castOther.getMotivoFaltaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFuncionarioCargoId();
         result = 37 * result + this.getMotivoFaltaId();
         return result;
   }   


}


