package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionarioAcidente generated by hbm2java
 */
@Entity
@Table(name="funcionario_acidente"
    ,schema="public"
)
public class FuncionarioAcidente  implements java.io.Serializable {


     private int id;
     private FuncionarioCargo funcionarioCargo;
     private int nivelLesao;
     private int perdaPorcentagem;
     private String descricao;
     private Date dataOcorrencia;

    public FuncionarioAcidente() {
    }

    public FuncionarioAcidente(int id, FuncionarioCargo funcionarioCargo, int nivelLesao, int perdaPorcentagem, String descricao, Date dataOcorrencia) {
       this.id = id;
       this.funcionarioCargo = funcionarioCargo;
       this.nivelLesao = nivelLesao;
       this.perdaPorcentagem = perdaPorcentagem;
       this.descricao = descricao;
       this.dataOcorrencia = dataOcorrencia;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

    
    @Column(name="nivel_lesao", nullable=false)
    public int getNivelLesao() {
        return this.nivelLesao;
    }
    
    public void setNivelLesao(int nivelLesao) {
        this.nivelLesao = nivelLesao;
    }

    
    @Column(name="perda_porcentagem", nullable=false)
    public int getPerdaPorcentagem() {
        return this.perdaPorcentagem;
    }
    
    public void setPerdaPorcentagem(int perdaPorcentagem) {
        this.perdaPorcentagem = perdaPorcentagem;
    }

    
    @Column(name="descricao", nullable=false, length=500)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ocorrencia", nullable=false, length=13)
    public Date getDataOcorrencia() {
        return this.dataOcorrencia;
    }
    
    public void setDataOcorrencia(Date dataOcorrencia) {
        this.dataOcorrencia = dataOcorrencia;
    }




}


