package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivoFalta generated by hbm2java
 */
@Entity
@Table(name="motivo_falta"
    ,schema="public"
)
public class MotivoFalta  implements java.io.Serializable {


     private int id;
     private String nome;
     private boolean atestado;
     private boolean desconta;
     private boolean ativo = true;

     private Set<FuncionarioCargoHasMotivoFalta> funcionarioCargoHasMotivoFaltas = new HashSet<FuncionarioCargoHasMotivoFalta>(0);

    public MotivoFalta() {
    }

     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=300)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="atestado", nullable=false, length=1)
    public boolean getAtestado() {
        return this.atestado;
    }
    
    public void setAtestado(boolean atestado) {
        this.atestado = atestado;
    }

    
    @Column(name="desconta", length=1)
    public boolean getDesconta() {
        return this.desconta;
    }
    
    public void setDesconta(boolean desconta) {
        this.desconta = desconta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivoFalta")
    public Set<FuncionarioCargoHasMotivoFalta> getFuncionarioCargoHasMotivoFaltas() {
        return this.funcionarioCargoHasMotivoFaltas;
    }
    
    public void setFuncionarioCargoHasMotivoFaltas(Set<FuncionarioCargoHasMotivoFalta> funcionarioCargoHasMotivoFaltas) {
        this.funcionarioCargoHasMotivoFaltas = funcionarioCargoHasMotivoFaltas;
    }

    public boolean isAtivo() {
        return ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


