package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivoFalta generated by hbm2java
 */
@Entity
@Table(name="motivo_falta"
    ,schema="public"
)
public class MotivoFalta  implements java.io.Serializable {


     private int id;
     private String nome;
     private char atestado;
     private Character desconta;
     private Set<FuncionarioCargoHasMotivoFalta> funcionarioCargoHasMotivoFaltas = new HashSet<FuncionarioCargoHasMotivoFalta>(0);

    public MotivoFalta() {
    }

	
    public MotivoFalta(int id, String nome, char atestado) {
        this.id = id;
        this.nome = nome;
        this.atestado = atestado;
    }
    public MotivoFalta(int id, String nome, char atestado, Character desconta, Set<FuncionarioCargoHasMotivoFalta> funcionarioCargoHasMotivoFaltas) {
       this.id = id;
       this.nome = nome;
       this.atestado = atestado;
       this.desconta = desconta;
       this.funcionarioCargoHasMotivoFaltas = funcionarioCargoHasMotivoFaltas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=300)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="atestado", nullable=false, length=1)
    public char getAtestado() {
        return this.atestado;
    }
    
    public void setAtestado(char atestado) {
        this.atestado = atestado;
    }

    
    @Column(name="desconta", length=1)
    public Character getDesconta() {
        return this.desconta;
    }
    
    public void setDesconta(Character desconta) {
        this.desconta = desconta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivoFalta")
    public Set<FuncionarioCargoHasMotivoFalta> getFuncionarioCargoHasMotivoFaltas() {
        return this.funcionarioCargoHasMotivoFaltas;
    }
    
    public void setFuncionarioCargoHasMotivoFaltas(Set<FuncionarioCargoHasMotivoFalta> funcionarioCargoHasMotivoFaltas) {
        this.funcionarioCargoHasMotivoFaltas = funcionarioCargoHasMotivoFaltas;
    }




}


