package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * NecessidadeEspecial generated by hbm2java
 */
@Entity
@Table(name="necessidade_especial"
    ,schema="public"
)
public class NecessidadeEspecial  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public NecessidadeEspecial() {
    }

	
    public NecessidadeEspecial(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public NecessidadeEspecial(int id, String nome, Set<Pessoa> pessoas) {
       this.id = id;
       this.nome = nome;
       this.pessoas = pessoas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pessoa_has_necessidade_especial", schema="public", joinColumns = { 
        @JoinColumn(name="necessidade_especial_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="pessoa_id", nullable=false, updatable=false) })
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


