package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name="parametro"
    ,schema="public"
)
public class Parametro  implements java.io.Serializable {


     private String chave;
     private String valor;

    public Parametro() {
    }

    public Parametro(String chave, String valor) {
       this.chave = chave;
       this.valor = valor;
    }
   
     @Id 

    
    @Column(name="chave", unique=true, nullable=false, length=100)
    public String getChave() {
        return this.chave;
    }
    
    public void setChave(String chave) {
        this.chave = chave;
    }

    
    @Column(name="valor", nullable=false)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


