package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PessoaCarteira generated by hbm2java
 */
@Entity
@Table(name="pessoa_carteira"
    ,schema="public"
)
public class PessoaCarteira  implements java.io.Serializable {


     private int pessoaId;
     private Pessoa pessoa;
     private String cnh;
     private String categoria;

    public PessoaCarteira() {
    }

    public PessoaCarteira(Pessoa pessoa, String cnh, String categoria) {
       this.pessoa = pessoa;
       this.cnh = cnh;
       this.categoria = categoria;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pessoa"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="pessoa_id", unique=true, nullable=false)
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="cnh", nullable=false, length=11)
    public String getCnh() {
        return this.cnh;
    }
    
    public void setCnh(String cnh) {
        this.cnh = cnh;
    }

    
    @Column(name="categoria", nullable=false, length=2)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }




}


