package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlanoAvaliacao generated by hbm2java
 */
@Entity
@Table(name="plano_avaliacao"
    ,schema="public"
)
public class PlanoAvaliacao  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Questao> questaos = new HashSet<Questao>(0);
     private Set<Vagas> vagases = new HashSet<Vagas>(0);

    public PlanoAvaliacao() {
    }

	
    public PlanoAvaliacao(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public PlanoAvaliacao(int id, String nome, Set<Questao> questaos, Set<Vagas> vagases) {
       this.id = id;
       this.nome = nome;
       this.questaos = questaos;
       this.vagases = vagases;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="plano_avaliacao_has_questao", schema="public", joinColumns = { 
        @JoinColumn(name="plano_avaliacao_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="questao_id", nullable=false, updatable=false) })
    public Set<Questao> getQuestaos() {
        return this.questaos;
    }
    
    public void setQuestaos(Set<Questao> questaos) {
        this.questaos = questaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planoAvaliacao")
    public Set<Vagas> getVagases() {
        return this.vagases;
    }
    
    public void setVagases(Set<Vagas> vagases) {
        this.vagases = vagases;
    }




}


