package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QualificacoesHasFuncionario generated by hbm2java
 */
@Entity
@Table(name="qualificacoes_has_funcionario"
    ,schema="public"
)
public class QualificacoesHasFuncionario  implements java.io.Serializable {


     private QualificacoesHasFuncionarioId id;
     private Funcionario funcionario;
     private Qualificacao qualificacao;
     private String certificado;
     private Date validade;

    public QualificacoesHasFuncionario() {
    }

	
    public QualificacoesHasFuncionario(QualificacoesHasFuncionarioId id, Funcionario funcionario, Qualificacao qualificacao) {
        this.id = id;
        this.funcionario = funcionario;
        this.qualificacao = qualificacao;
    }
    public QualificacoesHasFuncionario(QualificacoesHasFuncionarioId id, Funcionario funcionario, Qualificacao qualificacao, String certificado, Date validade) {
       this.id = id;
       this.funcionario = funcionario;
       this.qualificacao = qualificacao;
       this.certificado = certificado;
       this.validade = validade;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="qualificacaoId", column=@Column(name="qualificacao_id", nullable=false) ), 
        @AttributeOverride(name="funcionarioPessoaId", column=@Column(name="funcionario_pessoa_id", nullable=false) ) } )
    public QualificacoesHasFuncionarioId getId() {
        return this.id;
    }
    
    public void setId(QualificacoesHasFuncionarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_pessoa_id", nullable=false, insertable=false, updatable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qualificacao_id", nullable=false, insertable=false, updatable=false)
    public Qualificacao getQualificacao() {
        return this.qualificacao;
    }
    
    public void setQualificacao(Qualificacao qualificacao) {
        this.qualificacao = qualificacao;
    }

    
    @Column(name="certificado", length=100)
    public String getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="validade", length=13)
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }




}


