package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import br.com.empresa.rh.model.view.Folha;
import com.fasterxml.jackson.annotation.JsonView;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Qualificacao generated by hbm2java
 */
@Entity
@Table(name = "qualificacao", schema = "public"
)
@SequenceGenerator(name = "qualificacao_seq", sequenceName = "qualificacao_seq", initialValue = 1, allocationSize = 1)

public class Qualificacao implements java.io.Serializable {

    @JsonView({Folha.FuncionarioFicha.class})

    private int id;
    @JsonView({Folha.FuncionarioFicha.class})

    private String nome;
    @JsonView({Folha.FuncionarioFicha.class})
    private Integer cargaHoraria;
    @JsonView({Folha.FuncionarioFicha.class})
    private boolean certificado;
    @JsonView({Folha.FuncionarioFicha.class})
    private boolean validade;
    @JsonView({Folha.FuncionarioFicha.class})
    private String descricao;
    @JsonView({Folha.FuncionarioFicha.class})
    private boolean ativo = true;
    private Set<FuncionarioQualificacao> funcionarioQualificacaos = new HashSet<FuncionarioQualificacao>(0);

    public Qualificacao() {
    }

    public Qualificacao(int id, String nome, boolean certificado, boolean validade) {
        this.id = id;
        this.nome = nome;
        this.certificado = certificado;
        this.validade = validade;
    }

    public Qualificacao(int id, String nome, Integer cargaHoraria, boolean certificado, boolean validade, String descricao, Set<FuncionarioQualificacao> funcionarioQualificacaos) {
        this.id = id;
        this.nome = nome;
        this.cargaHoraria = cargaHoraria;
        this.certificado = certificado;
        this.validade = validade;
        this.descricao = descricao;
        this.funcionarioQualificacaos = funcionarioQualificacaos;
    }

    @Id

    @GeneratedValue(generator = "qualificacao_seq", strategy = GenerationType.SEQUENCE)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nome", nullable = false, length = 400)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "carga_horaria")
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }

    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    @Column(name = "certificado", nullable = false, length = 1)
    public boolean getCertificado() {
        return this.certificado;
    }

    public void setCertificado(boolean certificado) {
        this.certificado = certificado;
    }

    @Column(name = "validade", nullable = false, length = 1)
    public boolean getValidade() {
        return this.validade;
    }

    public void setValidade(boolean validade) {
        this.validade = validade;
    }

    @Column(name = "descricao", length = 2000)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qualificacao")
    public Set<FuncionarioQualificacao> getFuncionarioQualificacaos() {
        return this.funcionarioQualificacaos;
    }

    public void setFuncionarioQualificacaos(Set<FuncionarioQualificacao> funcionarioQualificacaos) {
        this.funcionarioQualificacaos = funcionarioQualificacaos;
    }

    public boolean isAtivo() {
        return ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

}
