package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Qualificacao generated by hbm2java
 */
@Entity
@Table(name="qualificacao"
    ,schema="public"
)
public class Qualificacao  implements java.io.Serializable {


     private int id;
     private String nome;
     private Integer cargaHoraria;
     private char certificado;
     private char validade;
     private String descricao;
     private boolean ativo = true;
     private Set<FuncionarioQualificacao> funcionarioQualificacaos = new HashSet<FuncionarioQualificacao>(0);

    public Qualificacao() {
    }

	
    public Qualificacao(int id, String nome, char certificado, char validade) {
        this.id = id;
        this.nome = nome;
        this.certificado = certificado;
        this.validade = validade;
    }
    public Qualificacao(int id, String nome, Integer cargaHoraria, char certificado, char validade, String descricao, Set<FuncionarioQualificacao> funcionarioQualificacaos) {
       this.id = id;
       this.nome = nome;
       this.cargaHoraria = cargaHoraria;
       this.certificado = certificado;
       this.validade = validade;
       this.descricao = descricao;
       this.funcionarioQualificacaos = funcionarioQualificacaos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=400)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="carga_horaria")
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    
    @Column(name="certificado", nullable=false, length=1)
    public char getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(char certificado) {
        this.certificado = certificado;
    }

    
    @Column(name="validade", nullable=false, length=1)
    public char getValidade() {
        return this.validade;
    }
    
    public void setValidade(char validade) {
        this.validade = validade;
    }

    
    @Column(name="descricao", length=2000)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="qualificacao")
    public Set<FuncionarioQualificacao> getFuncionarioQualificacaos() {
        return this.funcionarioQualificacaos;
    }
    
    public void setFuncionarioQualificacaos(Set<FuncionarioQualificacao> funcionarioQualificacaos) {
        this.funcionarioQualificacaos = funcionarioQualificacaos;
    }

    public boolean isAtivo() {
        return ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


