package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * QuestaoOpcao generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "questao_opcao_seq", sequenceName = "questao_opcao_seq", initialValue = 1, allocationSize = 1)
@Table(name = "questao_opcao", schema = "public"
)
public class QuestaoOpcao implements java.io.Serializable {

    private int id;
    private Questao questao;
    private String texto;
    private Set<Resposta> respostas = new HashSet<Resposta>(0);

    public QuestaoOpcao() {
    }

    public QuestaoOpcao(int id, Questao questao, String texto) {
        this.id = id;
        this.questao = questao;
        this.texto = texto;
    }

    public QuestaoOpcao(int id, Questao questao, String texto, Set<Resposta> respostas) {
        this.id = id;
        this.questao = questao;
        this.texto = texto;
        this.respostas = respostas;
    }

    @Id
    @GeneratedValue(generator = "questao_opcao_seq", strategy = GenerationType.SEQUENCE)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "questao_id", nullable = false)
    public Questao getQuestao() {
        return this.questao;
    }

    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

    @Column(name = "texto", nullable = false, length = 100)
    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questaoOpcao")
    public Set<Resposta> getRespostas() {
        return this.respostas;
    }

    public void setRespostas(Set<Resposta> respostas) {
        this.respostas = respostas;
    }

}
