package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resposta generated by hbm2java
 */
@Entity
@Table(name="resposta"
    ,schema="public"
)
public class Resposta  implements java.io.Serializable {


     private int id;
     private Candidato candidato;
     private Questao questao;
     private QuestaoOpcao questaoOpcao;
     private String descricao;

    public Resposta() {
    }

	
    public Resposta(int id, Candidato candidato, Questao questao) {
        this.id = id;
        this.candidato = candidato;
        this.questao = questao;
    }
    public Resposta(int id, Candidato candidato, Questao questao, QuestaoOpcao questaoOpcao, String descricao) {
       this.id = id;
       this.candidato = candidato;
       this.questao = questao;
       this.questaoOpcao = questaoOpcao;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidato_id", nullable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questao_id", nullable=false)
    public Questao getQuestao() {
        return this.questao;
    }
    
    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questao_opcao_id")
    public QuestaoOpcao getQuestaoOpcao() {
        return this.questaoOpcao;
    }
    
    public void setQuestaoOpcao(QuestaoOpcao questaoOpcao) {
        this.questaoOpcao = questaoOpcao;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


