package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sindicato generated by hbm2java
 */
@Entity
@Table(name="sindicato"
    ,schema="public"
)
public class Sindicato  implements java.io.Serializable {


     private int id;
     private Date nome;
     private BigDecimal desconto;
     private BigDecimal valorMensal;
     private Set<FuncionarioCargo> funcionarioCargos = new HashSet<FuncionarioCargo>(0);
     private Set<SindicatoHasFuncionarioCargo> sindicatoHasFuncionarioCargos = new HashSet<SindicatoHasFuncionarioCargo>(0);

    public Sindicato() {
    }

	
    public Sindicato(int id, Date nome) {
        this.id = id;
        this.nome = nome;
    }
    public Sindicato(int id, Date nome, BigDecimal desconto, BigDecimal valorMensal, Set<FuncionarioCargo> funcionarioCargos, Set<SindicatoHasFuncionarioCargo> sindicatoHasFuncionarioCargos) {
       this.id = id;
       this.nome = nome;
       this.desconto = desconto;
       this.valorMensal = valorMensal;
       this.funcionarioCargos = funcionarioCargos;
       this.sindicatoHasFuncionarioCargos = sindicatoHasFuncionarioCargos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nome", nullable=false, length=13)
    public Date getNome() {
        return this.nome;
    }
    
    public void setNome(Date nome) {
        this.nome = nome;
    }

    
    @Column(name="desconto", precision=10)
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }

    
    @Column(name="valor_mensal", precision=10)
    public BigDecimal getValorMensal() {
        return this.valorMensal;
    }
    
    public void setValorMensal(BigDecimal valorMensal) {
        this.valorMensal = valorMensal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sindicato")
    public Set<FuncionarioCargo> getFuncionarioCargos() {
        return this.funcionarioCargos;
    }
    
    public void setFuncionarioCargos(Set<FuncionarioCargo> funcionarioCargos) {
        this.funcionarioCargos = funcionarioCargos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sindicato")
    public Set<SindicatoHasFuncionarioCargo> getSindicatoHasFuncionarioCargos() {
        return this.sindicatoHasFuncionarioCargos;
    }
    
    public void setSindicatoHasFuncionarioCargos(Set<SindicatoHasFuncionarioCargo> sindicatoHasFuncionarioCargos) {
        this.sindicatoHasFuncionarioCargos = sindicatoHasFuncionarioCargos;
    }




}


