package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SindicatoHasFuncionarioCargo generated by hbm2java
 */
@Entity
@Table(name="sindicato_has_funcionario_cargo"
    ,schema="public"
)
public class SindicatoHasFuncionarioCargo  implements java.io.Serializable {


     private SindicatoHasFuncionarioCargoId id;
     private FuncionarioCargo funcionarioCargo;
     private Sindicato sindicato;
     private Date dataInicio;
     private Date dataFim;

    public SindicatoHasFuncionarioCargo() {
    }

    public SindicatoHasFuncionarioCargo(SindicatoHasFuncionarioCargoId id, FuncionarioCargo funcionarioCargo, Sindicato sindicato, Date dataInicio, Date dataFim) {
       this.id = id;
       this.funcionarioCargo = funcionarioCargo;
       this.sindicato = sindicato;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sindicatoId", column=@Column(name="sindicato_id", nullable=false) ), 
        @AttributeOverride(name="funcionarioCargoId", column=@Column(name="funcionario_cargo_id", nullable=false) ) } )
    public SindicatoHasFuncionarioCargoId getId() {
        return this.id;
    }
    
    public void setId(SindicatoHasFuncionarioCargoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_cargo_id", nullable=false, insertable=false, updatable=false)
    public FuncionarioCargo getFuncionarioCargo() {
        return this.funcionarioCargo;
    }
    
    public void setFuncionarioCargo(FuncionarioCargo funcionarioCargo) {
        this.funcionarioCargo = funcionarioCargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sindicato_id", nullable=false, insertable=false, updatable=false)
    public Sindicato getSindicato() {
        return this.sindicato;
    }
    
    public void setSindicato(Sindicato sindicato) {
        this.sindicato = sindicato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_fim", nullable=false, length=13)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }




}


