package br.com.empresa.rh.model;
// Generated 19/04/2016 00:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SindicatoHasFuncionarioCargoId generated by hbm2java
 */
@Embeddable
public class SindicatoHasFuncionarioCargoId  implements java.io.Serializable {


     private int sindicatoId;
     private int funcionarioCargoId;

    public SindicatoHasFuncionarioCargoId() {
    }

    public SindicatoHasFuncionarioCargoId(int sindicatoId, int funcionarioCargoId) {
       this.sindicatoId = sindicatoId;
       this.funcionarioCargoId = funcionarioCargoId;
    }
   


    @Column(name="sindicato_id", nullable=false)
    public int getSindicatoId() {
        return this.sindicatoId;
    }
    
    public void setSindicatoId(int sindicatoId) {
        this.sindicatoId = sindicatoId;
    }


    @Column(name="funcionario_cargo_id", nullable=false)
    public int getFuncionarioCargoId() {
        return this.funcionarioCargoId;
    }
    
    public void setFuncionarioCargoId(int funcionarioCargoId) {
        this.funcionarioCargoId = funcionarioCargoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SindicatoHasFuncionarioCargoId) ) return false;
		 SindicatoHasFuncionarioCargoId castOther = ( SindicatoHasFuncionarioCargoId ) other; 
         
		 return (this.getSindicatoId()==castOther.getSindicatoId())
 && (this.getFuncionarioCargoId()==castOther.getFuncionarioCargoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSindicatoId();
         result = 37 * result + this.getFuncionarioCargoId();
         return result;
   }   


}


