package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tabelas generated by hbm2java
 */
@Entity
@Table(name="tabelas"
    ,schema="public"
)
public class Tabelas  implements java.io.Serializable {


     private int id;
     private Date dataInicio;
     private String tipo;
     private Set<TabelaValores> tabelaValoreses = new HashSet<TabelaValores>(0);

    public Tabelas() {
    }

	
    public Tabelas(int id, Date dataInicio) {
        this.id = id;
        this.dataInicio = dataInicio;
    }
    public Tabelas(int id, Date dataInicio, String tipo, Set<TabelaValores> tabelaValoreses) {
       this.id = id;
       this.dataInicio = dataInicio;
       this.tipo = tipo;
       this.tabelaValoreses = tabelaValoreses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    
    @Column(name="tipo", length=10)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tabelas")
    public Set<TabelaValores> getTabelaValoreses() {
        return this.tabelaValoreses;
    }
    
    public void setTabelaValoreses(Set<TabelaValores> tabelaValoreses) {
        this.tabelaValoreses = tabelaValoreses;
    }




}


