package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSanguineo generated by hbm2java
 */
@Entity
@Table(name="tipo_sanguineo"
    ,schema="public"
)
public class TipoSanguineo  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Dependente> dependentes = new HashSet<Dependente>(0);

    public TipoSanguineo() {
    }

	
    public TipoSanguineo(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public TipoSanguineo(int id, String nome, Set<Dependente> dependentes) {
       this.id = id;
       this.nome = nome;
       this.dependentes = dependentes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoSanguineo")
    public Set<Dependente> getDependentes() {
        return this.dependentes;
    }
    
    public void setDependentes(Set<Dependente> dependentes) {
        this.dependentes = dependentes;
    }




}


