package br.com.empresa.rh.model;
// Generated 17/04/2016 21:10:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinculoEmpregaticio generated by hbm2java
 */
@Entity
@Table(name="vinculo_empregaticio"
    ,schema="public"
)
public class VinculoEmpregaticio  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

    public VinculoEmpregaticio() {
    }

	
    public VinculoEmpregaticio(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public VinculoEmpregaticio(int id, String nome, Set<Funcionario> funcionarios) {
       this.id = id;
       this.nome = nome;
       this.funcionarios = funcionarios;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vinculoEmpregaticio")
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }




}


